# To create and activate this environment:
#   conda env create -f environment.yml
#   conda activate lake-temp

name: lake-temp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - xarray
  - scipy
  - matplotlib
  - cartopy
  - geopandas
  - shapely
  - fiona
  - pyproj
  - gdal
  - netcdf4
  - cfgrib

  # Pip-only packages
  - pip
  - pip:
      - herbie-data
